name: Secret Demo Workflow

on:
  push:
    branches:
      - main

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Secret
        run: echo "API Key is ${{ secrets.API_KEY }}"
